# Hello world

In [1]:
x=input("Enter your name")
print("hello"+x+" bye")

Enter your nameBharath
helloBharath bye


In [3]:
x=input("Enter your name")
print("hello",x,"bye")

Enter your nameBharath
hello Bharath bye


In [4]:
a=5
b=10

In [5]:
b,a=a,b

In [6]:
print(a)

10


In [7]:
print(b)

5


In [8]:
x=input("Enter")
print(type(x))

EnterBharath
<class 'str'>


In [9]:
x=input("Enter")
print(type(x))

Enter10
<class 'str'>


In [10]:
5/3

1.6666666666666667

In [11]:
5%3

2

In [13]:
5//3

1

In [14]:
22/7

3.142857142857143

In [15]:
22//7

3

In [16]:
int(22/7)

3

In [17]:
x=(1,2,3)

In [21]:
x=[1,2,3,4,5]

In [29]:
x=123456
for i in str(x):
    print(int(i),type(int(i)))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
5 <class 'int'>
6 <class 'int'>


In [30]:
x=123456
sum=0
for i in str(x):
    sum=sum+int(i)
print(sum)

21


In [31]:
x=input("Enter a number :")
sum=0
for i in x:
    sum=sum+int(i)
print(sum)

Enter a number :123456
21


In [32]:
a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
c=int(input("Enter the third number: "))

if a<b:
    if a<c:
        print(a)
if b<a:
    if b<c:
        print(b)
if c<a:
    if c<b:
        print(c)

Enter the first number: 1
Enter the second number: 2
Enter the third number: 3
1


In [34]:
a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
c=int(input("Enter the third number: "))

if a<b and a<c:
    print(a)
if b<a and b<c:
    print(b)
if c<a and c<b:
    print(c)

Enter the first number: 7
Enter the second number: 2
Enter the third number: 5
2


In [37]:
a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
c=int(input("Enter the third number: "))

if a<b and a<c:
    print(a)
elif b<a and b<c:
    print(b)
else:
    print(c)

Enter the first number: 5
Enter the second number: 7
Enter the third number: 2
2


In [39]:
min=int(input("Enter a number :"))
for i in range(1,3):
    x=int(input("Enter a number :"))
    if x<min:
        min=x
print("Minimum value is ",min)
    

Enter a number :8
Enter a number :7
Enter a number :5
Minimum value is  5


In [41]:
list=[]
list.append(int(input("Enter a number")))

Enter a number12


In [42]:
print(list)

[12]


In [9]:
list=[]
for i in range(0,3):
    list.append(int(input("Enter a number :")))
list.sort()
print("The minimum value is ",list[0])

Enter a number :4
Enter a number :8
Enter a number :9
The minimum value is  4


# Numpy

In [1]:
import numpy as np

In [3]:
x=[1,2,3]

In [4]:
y=np.array(x)

In [5]:
y

array([1, 2, 3])

In [6]:
x

[1, 2, 3]

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
x=np.zeros(7)

In [10]:
x

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
type(x)

numpy.ndarray

In [12]:
type(x[0])

numpy.float64

In [13]:
x

array([0., 0., 0., 0., 0., 0., 0.])

In [14]:
y=[[1,2,3],[4,5,6],[7,8,9]]

In [15]:
z=np.array(y)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
l=z.copy()

In [17]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
l*z

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [19]:
print(l)
print(z)
print(l*z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [20]:
l.dot(z)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [21]:
x="bharath"

In [24]:
x[::-1]

'htarahb'

# Eigen Values and Vector

In [3]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.linalg.eigh(x)

(array([-3.15746784, -0.67276795, 18.8302358 ]),
 array([[-0.80238891,  0.43402538, -0.40962667],
        [-0.16812656, -0.82296167, -0.54264865],
        [ 0.57263033,  0.36654613, -0.73330651]]))

# Palindrome

In [7]:
x=input("Enter any thing :")
if(x==x[::-1]):
    print("Palindrome")
else:
    print("Not a Palindrome")

Enter any thing :telugu
Not a Palindrome
